### ISSUE TITLE
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://readthedocs.org/api/v3/projects/ansible-lint/redirects/

### ISSUE THREAD

**Issue by ssbarnea** [nextstrain/readthedocs-cli#8]
### Current Behavior

Despite using a valid token, now we see a 400 error code. I suspect that might have something to do with a change on RTD side.

### Expected behavior

Pass.

### Additional context

https://github.com/ansible/ansible-lint/actions/runs/12146851506/job/33871718725

```
rtd projects ansible-lint redirects sync -f docs/redirects.yml --wet-run
Creating: page /en/latest/default_rules/ → /rules/
Creating: page /rules/hg-latest/ → /rules/latest/
Creating: page /rules/meta-no-info/ → /rules/schemas/#schemameta
Creating: page /rules/deprecated-command-syntax/ → /rules/no-free-form/
Creating: page /default_rules/index/ → /rules/
Creating: sphinx_htmldir  → 
Traceback (most recent call last):
  File "/Users/ssbarnea/code/a/ansible-lint/.tox/redirects/bin/rtd", line 8, in <module>
    sys.exit(rtd())
             ~~~^^
  File "/Users/ssbarnea/code/a/ansible-lint/.tox/redirects/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/ssbarnea/code/a/ansible-lint/.tox/redirects/lib/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/ssbarnea/code/a/ansible-lint/.tox/redirects/lib/python3.13/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/ssbarnea/code/a/ansible-lint/.tox/redirects/lib/python3.13/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/ssbarnea/code/a/ansible-lint/.tox/redirects/lib/python3.13/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/ssbarnea/code/a/ansible-lint/.tox/redirects/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ssbarnea/code/a/ansible-lint/.tox/redirects/lib/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/ssbarnea/code/a/ansible-lint/.tox/redirects/lib/python3.13/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/ssbarnea/code/a/ansible-lint/.tox/redirects/lib/python3.13/site-packages/readthedocs_cli/__init__.py", line 177, in rtd_projects_redirects_sync
    api.v3.create_project_redirect(ctx.obj.project_slug, r)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ssbarnea/code/a/ansible-lint/.tox/redirects/lib/python3.13/site-packages/readthedocs_cli/api/v3.py", line 29, in create_project_redirect
    return POST(f"projects/{urlescape(project_slug)}/redirects/", redirect.to_dict())
  File "/Users/ssbarnea/code/a/ansible-lint/.tox/redirects/lib/python3.13/site-packages/readthedocs_cli/api/v3.py", line 70, in POST
    res.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/ssbarnea/code/a/ansible-lint/.tox/redirects/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://readthedocs.org/api/v3/projects/ansible-lint/redirects/
```

**Comment by tsibley** [comment]
A 400 implies to me we're sending it invalid data. This is probably related to #6.

This is also suggested to me by the way the redirect it was trying to create was described in info messages before the traceback:

```
Creating: sphinx_htmldir  → 
```
